#//stage

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Minor_Projcet_jbdl61?createDatabaseIfNotExist=true
    username: root
    password: Root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug

server:
  port: 9090

custom_property:
  secret_key: fhcj1534

book:
  return:
    due_date: 14

users:
  authority:
    student: std
    admin: adm
